<!doctype html>
<html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><link rel="stylesheet" href="/public/css/app.css">
<title>Admin · <?= htmlspecialchars($application['name']) ?></title><body class="outdoor-mode">
<?php require __DIR__ . '/../partials/header.php'; ?>
<main class="auth-page account-page">
  <nav class="account-tabs" aria-label="Sections de l’administration">
    <a class="<?= $tab === 'profil' ? 'active' : '' ?>" href="/mon-compte?onglet=profil">Mon profil</a>
    <a class="<?= $tab === 'plantations' ? 'active' : '' ?>" href="/mon-compte?onglet=plantations">Plantations</a>
    <?php if ($isAdministrator): ?><a class="<?= $tab === 'utilisateurs' ? 'active' : '' ?>" href="/mon-compte?onglet=utilisateurs">Utilisateurs</a><?php endif; ?>
  </nav>

  <?php if ($tab === 'profil'): ?>
    <h2>Informations personnelles</h2><p>Rôle : <?= htmlspecialchars(str_replace('_', ' ', $user['role'])) ?></p>
    <form method="post" action="/mon-compte"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><label>Prénom<input name="first_name" value="<?= htmlspecialchars($user['first_name']) ?>" required></label><label>Nom<input name="last_name" value="<?= htmlspecialchars($user['last_name']) ?>" required></label><label>E-mail<input name="email" type="email" value="<?= htmlspecialchars($user['email']) ?>" required></label><label>Date d’inscription<input value="<?= htmlspecialchars((new DateTimeImmutable($user['created_at']))->format('d/m/Y')) ?>" readonly></label><label>Nouveau mot de passe <small>Laisser vide pour ne pas le modifier · 12 caractères minimum</small><input name="password" type="password" minlength="12" autocomplete="new-password"></label><button>Enregistrer</button></form>
  <?php elseif ($tab === 'plantations'): ?>
    <h2>Toutes mes propositions</h2>
    <div class="contribution-counts"><span><?= $counts['proposed'] ?> proposées</span><span><?= $counts['validated'] ?> validées</span><span><?= count($displayFeatures) ?> arbres proposés</span><span><?= $counts['planted'] ?> arbres plantés</span></div>
    <div class="plantations-workspace"><section class="proposal-admin-list"><h3>Liste des propositions</h3><?php if ($displayFeatures === []): ?><p>Aucune plantation.</p><?php endif; ?><?php foreach ($displayFeatures as $feature): $properties = $feature['properties'] ?? []; $coordinates = $feature['geometry']['coordinates'] ?? [null, null]; $id = (string) ($properties['id'] ?? ''); ?>
      <?php if ($isAdministrator): ?><form class="proposal-admin-card" data-proposal-id="<?= htmlspecialchars($id) ?>" method="post" action="/admin/propositions/modifier"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="id" value="<?= htmlspecialchars($id) ?>">
        <label>Essence<select name="species"><?php foreach ($planting['allowed_species'] as $species): ?><option value="<?= htmlspecialchars($species) ?>" <?= ($properties['species'] ?? '') === $species ? 'selected' : '' ?>><?= htmlspecialchars($species) ?></option><?php endforeach; ?></select></label>
        <fieldset><legend>Objectifs <small>3 maximum</small></legend><div class="objective-grid admin-objectives"><?php foreach ($planting['objectives'] as $key => $objective): ?><label class="objective"><input type="checkbox" name="objectives[]" value="<?= htmlspecialchars($key) ?>" <?= in_array($key, $properties['objectives'] ?? [], true) ? 'checked' : '' ?>><span class="objective-tile"><span class="objective-icon"><?= htmlspecialchars($objective['icon']) ?></span><span><?= htmlspecialchars($objective['label']) ?></span></span></label><?php endforeach; ?></div></fieldset>
        <label>Statut<select name="status"><?php foreach ($statuses as $value => $label): ?><option value="<?= htmlspecialchars($value) ?>" <?= ($properties['status'] ?? 'a_valider') === $value ? 'selected' : '' ?>><?= htmlspecialchars($label) ?></option><?php endforeach; ?></select></label><div class="coordinate-fields"><label>Longitude<input type="number" name="longitude" step="any" value="<?= htmlspecialchars((string) $coordinates[0]) ?>" required></label><label>Latitude<input type="number" name="latitude" step="any" value="<?= htmlspecialchars((string) $coordinates[1]) ?>" required></label></div><button>Enregistrer</button>
      </form><?php else: ?><article class="proposal-admin-card" data-proposal-id="<?= htmlspecialchars($id) ?>"><h3><?= htmlspecialchars((string) ($properties['species'] ?? 'Plantation')) ?></h3><p><?= htmlspecialchars(implode(', ', $properties['objectives'] ?? [])) ?></p><p><?= htmlspecialchars($statuses[$properties['status'] ?? 'a_valider'] ?? 'Proposée') ?></p></article><?php endif; ?>
    <?php endforeach; ?></section><aside class="plantations-map-panel"><h3>Carte</h3><p><?= $isAdministrator ? 'Faites glisser un repère pour modifier ses coordonnées.' : 'Vos propositions géolocalisées.' ?></p><div id="plantations-map" class="account-map"></div></aside></div>
  <?php elseif ($tab === 'utilisateurs'): ?>
    <h2>Utilisateurs</h2><table class="users-table"><thead><tr><th>Nom</th><th>E-mail</th><th>Rôle</th><th>Action</th></tr></thead><tbody><?php foreach ($users as $listedUser): ?><tr><td><?= htmlspecialchars($listedUser['first_name'] . ' ' . $listedUser['last_name']) ?></td><td><?= htmlspecialchars($listedUser['email']) ?></td><td><?= htmlspecialchars(str_replace('_', ' ', $listedUser['role'])) ?></td><td><?php if ($listedUser['role'] === 'super_administrateur'): ?>Protégé<?php elseif ($user['role'] === 'administrateur' && $listedUser['role'] === 'contributeur'): ?><form method="post" action="/admin/utilisateurs/role"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="user_id" value="<?= htmlspecialchars($listedUser['id']) ?>"><input type="hidden" name="role" value="administrateur"><button>Passer administrateur</button></form><?php elseif ($user['role'] === 'super_administrateur' && $listedUser['role'] === 'administrateur'): ?><div class="inline-actions"><form method="post" action="/admin/utilisateurs/role"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="user_id" value="<?= htmlspecialchars($listedUser['id']) ?>"><input type="hidden" name="role" value="contributeur"><button>Rétrograder</button></form><form method="post" action="/admin/utilisateurs/role"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="user_id" value="<?= htmlspecialchars($listedUser['id']) ?>"><input type="hidden" name="role" value="super_administrateur"><button>Passer super-admin</button></form></div><?php endif; ?></td></tr><?php endforeach; ?></tbody></table>
  <?php endif; ?>
</main><?php require __DIR__ . '/../partials/footer.php'; ?>
<?php if ($tab === 'plantations'): ?><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const proposalFeatures=<?= json_encode($displayFeatures, JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>;const canEdit=<?= $isAdministrator ? 'true' : 'false' ?>;const map=L.map('plantations-map').setView([47.531,-0.102],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);const cards=[...document.querySelectorAll('[data-proposal-id]')];const selectProposal=id=>{cards.forEach(card=>{card.hidden=card.dataset.proposalId!==id;});const card=document.querySelector(`[data-proposal-id="${id}"]`);if(card){card.scrollIntoView({behavior:'smooth',block:'center'});}};if(proposalFeatures.length>1)cards.forEach(card=>{card.hidden=true;});const markers=[];proposalFeatures.forEach(feature=>{const [lng,lat]=feature.geometry.coordinates;const marker=L.marker([lat,lng],{draggable:canEdit}).addTo(map);marker.bindPopup(`<strong>${feature.properties.species||'Plantation'}</strong>`);marker.on('click',()=>selectProposal(feature.properties.id));markers.push(marker);if(canEdit){marker.on('dragend',()=>{const position=marker.getLatLng();const form=document.querySelector(`[data-proposal-id="${feature.properties.id}"]`);if(form){form.querySelector('[name="longitude"]').value=position.lng.toFixed(6);form.querySelector('[name="latitude"]').value=position.lat.toFixed(6);selectProposal(feature.properties.id);}});}});if(markers.length){map.fitBounds(L.featureGroup(markers).getBounds(),{padding:[24,24]});}document.querySelectorAll('.admin-objectives').forEach(grid=>grid.addEventListener('change',event=>{if(grid.querySelectorAll('input:checked').length>3){event.target.checked=false;window.alert('Trois objectifs maximum.');}}));</script><?php endif; ?>
</body></html>
